### ISSUE TITLE
Overflow in range() when unhiding

### ISSUE THREAD

**Issue by Wo1v3r** [RobinDavid/LSB-Steganography#11]
Trying to unhide a png with a hidden text, recieving that error:

`python LSBSteg.py -steg-image steganography_lsb.png -out steg.bin
Traceback (most recent call last):
  File "LSBSteg.py", line 242, in <module>
    main(av)
  File "LSBSteg.py", line 236, in main
    binary_steg_reveal(args.steg_image, args.out)
  File "LSBSteg.py", line 212, in binary_steg_reveal
    bin = steg.unhideBin()
  File "LSBSteg.py", line 194, in unhideBin
    for i in range(l):
OverflowError: range() result has too many items`

**Comment by MaxToyberman** [comment]
range() is limited in python2 ,use python3 or xrange instead of range @Wo1v3r

**Comment by Wo1v3r** [comment]
roger ty :)
