### ISSUE TITLE
OverflowError

### ISSUE THREAD

**Issue by xiaolulwr** [RobinDavid/LSB-Steganography#13]
$ ./LSBSteg.py -steg-image flag.png -out res

Traceback (most recent call last):
  File "./LSBSteg.py", line 242, in <module>
    main(av)
  File "./LSBSteg.py", line 236, in main
    binary_steg_reveal(args.steg_image, args.out)
  File "./LSBSteg.py", line 212, in binary_steg_reveal
    bin = steg.unhideBin()
  File "./LSBSteg.py", line 194, in unhideBin
    for i in range(l):
OverflowError: range() result has too many items

**Comment by colundrum** [comment]
Hi,
I've the same error.
Can you patch it please ?
Thanks

**Comment by RobinDavid** [comment]
I have updated LSBSteg. If you can reproduce the error, can you upload the picture and reopening the issue ?
