### ISSUE TITLE
Overflow error

### ISSUE THREAD

**Issue by felbinger** [RobinDavid/LSB-Steganography#17]
Hello,
I don't get your script working. I had to install the modules python-opencv and python-docopt via apt (working on debian), to fix the import errors. But now I get an Overflow Error:

`Traceback (most recent call last):
  File "LSBSteg.py", line 189, in <module>
    main()
  File "LSBSteg.py", line 183, in main
    raw = steg.decode_binary()
  File "LSBSteg.py", line 165, in decode_binary
    for i in range(l):
OverflowError: range() result has too many items`

I am running the command: `python LSBSteg.py decode --in=export.png --out=outfile`
How can I fix it?
Thanks in advance.

**Comment by EllisonFord** [comment]
I have the same problem, if anyone knows how to solve this.

**Comment by felbinger** [comment]
I couldn't solve the problem. I used another tool for the stego challenge I was working on.

**Comment by SebastienTainon** [comment]
@felbinger Which one did you use? Thanks!
