### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by pdelteil** [RobinDavid/LSB-Steganography#20]
LSBSteg.py decode -i file.png -o output.txt

Traceback (most recent call last):
  File "/usr/local/bin/LSBSteg.py", line 189, in <module>
    main()
  File "/usr/local/bin/LSBSteg.py", line 183, in main
    raw = steg.decode_binary()
  File "/usr/local/bin/LSBSteg.py", line 165, in decode_binary
    for i in range(l):
MemoryError

**Comment by RobinDavid** [comment]
Hi Philippe,
Sorry for the delay of response.
Are you sure, you correctly did embbed an hidden message in ``file.png`` beforehand ?
That means you filled your RAM because the size of the file read by ``l = int(self.read_bits(64), 2)`` is incorrect.
